#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/collectd ]; then
    echo "Installing collectd stuff."

    rm -rf $OPENSHIFT_DATA_DIR/build_cd
    mkdir $OPENSHIFT_DATA_DIR/build_cd
    cd $OPENSHIFT_DATA_DIR/build_cd

    curl -L -O http://sourceforge.net/projects/libdbi/files/libdbi/libdbi-0.9.0/libdbi-0.9.0.tar.gz
    curl -L -O http://sourceforge.net/projects/libdbi-drivers/files/libdbi-drivers/libdbi-drivers-0.9.0/libdbi-drivers-0.9.0.tar.gz
    tar fxz libdbi-0.9.0.tar.gz
    tar fxz libdbi-drivers-0.9.0.tar.gz

    cd libdbi-0.9.0
    ./configure --disable-docs --prefix=$OPENSHIFT_DATA_DIR/dbi
    make
    make install

    cd ..
    cd libdbi-drivers-0.9.0
    ./configure --disable-docs --prefix=$OPENSHIFT_DATA_DIR/dbi --with-mysql --with-dbi-incdir=$OPENSHIFT_DATA_DIR/dbi/include --with-dbi-libdir=$OPENSHIFT_DATA_DIR/dbi/lib
    make
    make install

    wget https://collectd.org/files/collectd-5.4.1.tar.bz2
    tar jxf collectd-5.4.1.tar.bz2
    cd collectd-5.4.1
    ./configure --prefix=$OPENSHIFT_DATA_DIR/collectd --with-libdbi=$OPENSHIFT_DATA_DIR/dbi
    make 'CFLAGS=-Wno-error=deprecated-declarations'
    make install

    cd $OPENSHIFT_DATA_DIR
    rm -rf $OPENSHIFT_DATA_DIR/build_cd
else
    echo "Skip collectd install."
fi
