#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -f $OPENSHIFT_DATA_DIR/quiz/config.ini ]; then
echo "Updating config.ini..."
cp $OPENSHIFT_REPO_DIR/misc/config.ini $OPENSHIFT_DATA_DIR/quiz
fi

if [ ! -f $OPENSHIFT_DATA_DIR/quiz/uwsgi.ini ]; then
echo "Updating uwsgi.ini..."
cp $OPENSHIFT_REPO_DIR/misc/uwsgi.ini $OPENSHIFT_DATA_DIR/quiz
fi

if [ ! -f $OPENSHIFT_DATA_DIR/quiz/nginx.conf ]; then
echo "Updating nginx.conf..."
cp $OPENSHIFT_REPO_DIR/misc/nginx.conf $OPENSHIFT_DATA_DIR/quiz
fi

echo "Pre-processing nginx config..."
env | sed 's/[\%]/\\&/g;s/\([^=]*\)=\(.*\)/s%${\1}%\2%/' > $OPENSHIFT_TMP_DIR/sed.script
cat $OPENSHIFT_DATA_DIR/quiz/nginx.conf | sed -f $OPENSHIFT_TMP_DIR/sed.script > $OPENSHIFT_DATA_DIR/nginx/conf/nginx.conf

if [ ! -d $OPENSHIFT_DATA_DIR/quiz/img ]; then
echo "Unpacking images..."
unzip -o $OPENSHIFT_REPO_DIR/misc/img.zip -d $OPENSHIFT_DATA_DIR/quiz/img
fi

# Generate documantation (if needed).
if [ -d $OPENSHIFT_DATA_DIR/quiz/apidoc ]; then
$OPENSHIFT_DATA_DIR/bin/sphinx-build -b html  $OPENSHIFT_REPO_DIR/doc $OPENSHIFT_DATA_DIR/quiz/apidoc
fi
