#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate

if [ ! -d $OPENSHIFT_DATA_DIR/quiz ]; then
echo "Creating quiz data dir..."
mkdir $OPENSHIFT_DATA_DIR/quiz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/quiz/img ]; then
echo "Unpacking images to quiz data dir..."
unzip -o $OPENSHIFT_REPO_DIR/misc/img.zip -d $OPENSHIFT_DATA_DIR/quiz/img
fi

if [ ! -d $OPENSHIFT_REPO_DIR/wsgi/static ]; then
echo "Creating wsgi/static..."
mkdir $OPENSHIFT_REPO_DIR/wsgi/static
ln -s $OPENSHIFT_DATA_DIR/quiz/img $OPENSHIFT_REPO_DIR/wsgi/static/qimg
ln -s $OPENSHIFT_REPO_DIR/wsgi/quiz/ui/static $OPENSHIFT_REPO_DIR/wsgi/static/ui
fi

# Generate translations & build assets
cd $OPENSHIFT_REPO_DIR
pybabel compile -d wsgi/quiz/ui/translations -D ui
python manage.py assets build
