#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate

env | sed 's/[\%]/\\&/g;s/\([^=]*\)=\(.*\)/s%${\1}%\2%/' > $OPENSHIFT_TMP_DIR/sed.script

function expand_env_vars() {
    local SRC=$1
    local DEST=$2
    cat $SRC | sed -f $OPENSHIFT_TMP_DIR/sed.script > $DEST
}


if [ ! -d $OPENSHIFT_DATA_DIR/quiz ]; then
echo "Creating quiz data dir..."
mkdir $OPENSHIFT_DATA_DIR/quiz
fi

if [ ! -d $OPENSHIFT_DATA_DIR/quiz/img ]; then
echo "Unpacking images to quiz data dir..."
unzip -o $OPENSHIFT_REPO_DIR/misc/img.zip -d $OPENSHIFT_DATA_DIR/quiz/img
fi

echo "Creating wsgi/static..."
ln -s $OPENSHIFT_REPO_DIR/wsgi/quiz/static $OPENSHIFT_REPO_DIR/wsgi/static
ln -s $OPENSHIFT_DATA_DIR/quiz/img $OPENSHIFT_REPO_DIR/wsgi/static/qimg
ln -s $OPENSHIFT_REPO_DIR/web $OPENSHIFT_REPO_DIR/wsgi/static/oldfrontend

# Generate translations & build assets
cd $OPENSHIFT_REPO_DIR
pybabel compile -d wsgi/quiz/translations
python manage.py assets build

echo "Creating collectd.conf"
expand_env_vars $OPENSHIFT_REPO_DIR/misc/metrics/collectd.conf $OPENSHIFT_DATA_DIR/collectd/etc/collectd.conf
