#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Create quiz data directory
if [ ! -d $OPENSHIFT_DATA_DIR/quiz ]; then
mkdir $OPENSHIFT_DATA_DIR/quiz
fi

# Create directory for pid and socket files.
if [ ! -d $OPENSHIFT_DATA_DIR/pid ]; then
mkdir $OPENSHIFT_DATA_DIR/pid
fi

if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then

# install python 2.7.3 on builder gear
cd $OPENSHIFT_TMP_DIR
wget http://python.org/ftp/python/2.7.3/Python-2.7.3.tar.bz2
tar jxf Python-2.7.3.tar.bz2
cd Python-2.7.3
./configure --prefix=$OPENSHIFT_DATA_DIR
make install

export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH

# Install setuptools.
cd $OPENSHIFT_TMP_DIR
wget http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz
tar zxf setuptools-0.6c11.tar.gz
cd setuptools-0.6c11
python setup.py install

# Install pip.
cd $OPENSHIFT_TMP_DIR
wget http://pypi.python.org/packages/source/p/pip/pip-1.1.tar.gz
tar zxf pip-1.1.tar.gz
cd pip-1.1
python setup.py install

# Cleanup.
cd $OPENSHIFT_TMP_DIR
rm -rf Python-2.7.3.tar.bz2
rm -rf setuptools-0.6c11.tar.gz
rm -rf pip-1.1.tar.gz
rm -Rf Python-2.7.3
rm -Rf setuptools-0.6c11
rm -Rf pip-1.1
fi

# Build nginx.
if [ ! -d $OPENSHIFT_DATA_DIR/nginx ]; then
cd $OPENSHIFT_TMP_DIR

wget http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.32.tar.bz2
wget http://zlib.net/zlib-1.2.8.tar.bz2
wget http://nginx.org/download/nginx-1.2.8.tar.gz

tar jxf pcre-8.32.tar.bz2
tar zxf zlib-1.2.8.tar.gz
tar zxf nginx-1.2.8.tar.gz

cd nginx-1.2.8
./configure --with-zlib=../zlib-1.2.8 --with-pcre=../pcre-8.32  --prefix=$OPENSHIFT_DATA_DIR/nginx
make install

# Cleanup.
cd $OPENSHIFT_TMP_DIR
rm -rf pcre-8.32.tar.bz2
rm -rf zlib-1.2.8.tar.gz
rm -rf nginx-1.2.8.tar.gz
rm -Rf pcre-8.32
rm -Rf zlib-1.2.8
rm -Rf nginx-1.2.8
fi
