version: '2'

services:
   db:
     image: mysql:5.5
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306" # for debug (have to be removed in future)
     environment:
       MYSQL_ROOT_PASSWORD: LqWA9M42
       MYSQL_DATABASE: quiz
       MYSQL_USER: quiz
       MYSQL_PASSWORD: u16F6gip

   web:
     depends_on:
       - db
     image: quiz
     ports:
       - "80:80"
     volumes:
      - data_vol:/var/www/quiz2/data/sessions
#     restart: always
# Temporary
     environment:
       DB_URI: mysql://quiz:u16F6gip@db:3306/
       DB_USER: quiz
       DB_PASS: u16F6gip
       DB_HOST: db
       DB_NAME: quiz
       ACCOUNTS_URL: ${ACCOUNTS_URL}
volumes:
    data_vol:
    db_data:
