version: '2'

services:
   db:
     image: ${MYSQL_IMAGE}
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "127.0.0.1:3306:3306" # for debug (have to be removed in future)
     environment:
       MYSQL_ROOT_PASSWORD: LqWA9M42
       MYSQL_DATABASE: quiz
       MYSQL_USER: quiz
       MYSQL_PASSWORD: u16F6gip

   web:
     depends_on:
       - db
     image: quiz
     volumes:
      - data_vol:/var/www/quiz2/data/sessions
     restart: always
     env_file:
      - web.env

   proxy:
     privileged: true
     depends_on:
      - web
     image: front_proxy
     volumes:
      - /etc/letsencrypt:/etc/letsencrypt
     ports:
       - "80:80"
       - "443:443"
volumes:
    data_vol:
    db_data:
