version: '2'

services:
#   db:
#     image: mysql:5.5
#     volumes:
#       - db_data:/var/lib/mysql
#     restart: always
#     ports:
#       - "3306:3306" # for debug (have to be removed in future)
#     environment:
#       MYSQL_ROOT_PASSWORD: quiz
#       MYSQL_DATABASE: quiz
#       MYSQL_USER: quiz
#       MYSQL_PASSWORD: quiz

   web:
#     depends_on:
#       - db
     image: quiz
     ports:
       - "80:80"
     volumes:
      - data_vol:/var/www/quiz2/data/sessions
#     restart: always
# Temporary
     environment:
       DB_URI: mysql://root:quiz@51.15.47.144:3306/
       DB_USER: root
       DB_PASS: quiz
       DB_HOST: 51.15.47.144
       DB_NAME: quiz
volumes:
    data_vol:
#    db_data:
